### ISSUE TITLE
Host name shows up as None in flow meta info

### ISSUE THREAD

**Issue by vthapar** [shague/odltools#16]
Table:44, Host:None, FlowId:SNAT.4579365583386.44.100021.10.10.10.7.49152,VpnId:100021/0x30d6a,Reason:None

Currently code picks hostname form description field in opendaylight-inventory operational. Probably due to bug or way OFP works, it is coming in empty even though hostname is configured. Should pick it off hostname field in OVSDB Topology.

**Comment by shague** [comment]
hostname is pulled from ovsdb topology from odl_os_hostconfig_hostid. This assumes hostconfig has been setup so maybe that is different in your test? Are you saying the hostname field below is what should be used? If so, that is just localhost most of the time.

"ovsdb:openvswitch-external-ids": [
                        {
                            "external-id-key": "hostname",
                            "external-id-value": "localhost"
                        },
                        {
                            "external-id-key": "odl_os_hostconfig_hostid",
                            "external-id-value": "releng-45483-309-2-devstack-pike-1.vexxhost.net"
                        },
